'use client'

import { useChatStore } from '@/stores/chatStore'
import { useMapStore } from '@/stores/mapStore'
import { MessageList } from './MessageList'
import { ChatInput } from './ChatInput'
import { toast } from 'sonner'

interface ToolResult {
  tool: string
  result?: {
    elements: Array<unknown>
    summary: string
    suggestedViewState?: {
      longitude: number
      latitude: number
      zoom: number
    }
  }
  error?: string
}

interface ChatResponse {
  content: string
  toolResults?: ToolResult[]
}

export function ChatPanel() {
  const { addMessage, setLoading, messages } = useChatStore()
  const { addElements, setViewState } = useMapStore()

  const handleSend = async (content: string) => {
    // Add user message
    addMessage('user', content)
    setLoading(true)

    try {
      // Send message to chat API (which now handles tool calling)
      const chatResponse = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: [
            ...messages.map((m) => ({ role: m.role, content: m.content })),
            { role: 'user', content },
          ],
        }),
      })

      if (!chatResponse.ok) {
        throw new Error('Failed to get chat response')
      }

      const data: ChatResponse = await chatResponse.json()

      // Add assistant message
      addMessage('assistant', data.content)

      // Handle tool results (map elements generated by the model's decision)
      if (data.toolResults && data.toolResults.length > 0) {
        for (const toolResult of data.toolResults) {
          if (toolResult.tool === 'generate_map_elements' && toolResult.result) {
            const { elements, suggestedViewState } = toolResult.result

            if (elements && elements.length > 0) {
              addElements(elements as Parameters<typeof addElements>[0])
              toast.success(`Added ${elements.length} elements to map`)
            }

            if (suggestedViewState) {
              setViewState(suggestedViewState)
            }
          } else if (toolResult.error) {
            toast.error(toolResult.error)
          }
        }
      }
    } catch (error) {
      console.error('Chat error:', error)
      addMessage('assistant', 'Sorry, I encountered an error. Please try again.')
      toast.error('Failed to process your request')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex flex-col h-full bg-background">
      <div className="px-4 py-3 border-b">
        <h2 className="font-semibold">Chat</h2>
      </div>
      <MessageList />
      <ChatInput onSend={handleSend} />
    </div>
  )
}
